platformName=ANDROID
automationName=UiAutomator2
deviceName=emulator-5554
platformVersion=13
app=apps/LFXTestV0.0.3.apk
appPackage=com.lfx
appActivity=com.lfx.MainActivity
noReset=false
fullReset=false
autoGrantPermissions=true
newCommandTimeout=300
adbExecTimeout=20000
androidInstallTimeout=120000


# ============================================
# LFX App Configuration
# UPDATE THESE VALUES AFTER RUNNING aapt COMMAND!
# ============================================
app.path=C:\Users\Admin\qa\MobileAutomationFramework\apps\LFXTestV0.0.3.apk
